basic:
    name: jadebikeloans.com.au
    environments:
        production: 'https://jadebikeloans.com.au'
        staging: 'https://staging.jadebikeloans.com.au'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - /approval
        - /blog
        - /blog/bike-buying-articles/new-enduro-pricing-released-get-your-triumph-motorcycles-finance-now
        - /contact-us
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
